name: nlp
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchaudio
  - torchvision
  - cudatoolkit=11.1
  - tensorboard
  - transformers
  - sentencepiece
  - beautifulsoup4
  - datasets
  - scikit-learn
